---
Name: silverstripe-deepl-translator
After: fluentcms
---

SilverStripe\Admin\LeftAndMain:
    extra_requirements_javascript:
        - arillo/silverstripe-deepl-translator:client/deepl.js

# ---
# Name: autotranslate-routes
# After:
#     - rootroutes
#     - coreroutes
# ---
# SilverStripe\Control\Director:
#     rules:
#         autotranslate//translate: Bratiask\Autotranslate\Controller\GoogleTranslateController