---
Name: silverstripe-deepl-translator
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - arillo/silverstripe-deepl-translator:client/deepl.css
  extra_requirements_javascript:
    - arillo/silverstripe-deepl-translator:client/deepl.js

---
Name: silverstripe-deepl-translator-routes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    api/deepl: Arillo\Deepl\TranslationController
    # api/deepl/translate: Arillo\Deepl\TranslationController

SilverStripe\SiteConfig\SiteConfig:
  extensions:
   - Arillo\Deepl\SiteConfig

SilverStripe\Admin\LeftAndMain:
  extensions:
    DeeplCMSMainExtension: Arillo\Deepl\DeeplCMSMainExtension
